trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(7ec5dade-3faa-4fd5-a30b-a0b61b765338)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t baluacr.azurecr.io/web-game:tag 2048-game
            az acr login -n baluacr
            docker push baluacr.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1(7ec5dade-3faa-4fd5-a30b-a0b61b765338)'
    azureResourceGroup: 'aksrg'
    kubernetesCluster: 'AKSCluster'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1(1)(7ec5dade-3faa-4fd5-a30b-a0b61b765338)'
    azureContainerRegistry: 'baluacr.azurecr.io'
    forceUpdate: false